"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
const express_1 = require("express");
const skillController_1 = require("../controllers/skillController");
const techUserController_1 = require("../controllers/techUserController");
const authMiddleware_1 = require("../middleware/authMiddleware");
const skill_validator_1 = require("../validators/skill.validator");
const validate_1 = require("../middleware/validate");
const userRouters = (0, express_1.Router)();
userRouters.post("/chooseSkill/:id", authMiddleware_1.auth, skillController_1.chooseSkill);
userRouters.post("/ChooseTrack/:id", authMiddleware_1.auth, techUserController_1.ChooseTrack);
userRouters.get("/GetTracks", authMiddleware_1.auth, techUserController_1.GetTracks);
userRouters.get("/GetRoadmaps/:id", authMiddleware_1.auth, techUserController_1.GetRoadmaps);
userRouters.get("/user/skills", authMiddleware_1.auth, techUserController_1.getUserSkills);
userRouters.get("/skills", authMiddleware_1.auth, techUserController_1.GetSkills);
userRouters.post("/user/skills", authMiddleware_1.auth, (0, validate_1.validate)(skill_validator_1.addSkillSchema), techUserController_1.addUserSkill);
userRouters.post("/user/progress/:roadmapId/topics/:topicId/complete", authMiddleware_1.auth, techUserController_1.completeTopic);
userRouters.post("/user/progress/complete", authMiddleware_1.auth, techUserController_1.completeTopic);
exports.default = userRouters;
